use super::command_runner::{run_specs, CommandSpec};
use super::event_sink::EventSink;

pub async fn run_audio_doctor(sink: EventSink) -> Vec<String>
{
    let specs = vec![
        CommandSpec::powershell("audio", "audio_preflight_snapshot", r#"$devices=Get-PnpDevice -ErrorAction SilentlyContinue | Where-Object { $_.Class -in @('AudioEndpoint','MEDIA','Sound') -or $_.FriendlyName -match 'audio|sound|realtek|nvidia high definition|bluetooth|usb audio' }; $services=Get-Service -Name Audiosrv,AudioEndpointBuilder,PlugPlay -ErrorAction SilentlyContinue; [PSCustomObject]@{AudioDeviceCount=($devices|Measure-Object).Count;Devices=$devices;Services=$services} | ConvertTo-Json -Compress -Depth 5"#, 120),
        CommandSpec::powershell("audio", "audio_device_scan", r#"Get-PnpDevice -ErrorAction SilentlyContinue | Where-Object { $_.Class -in @('AudioEndpoint','MEDIA','Sound') -or $_.FriendlyName -match 'audio|sound|realtek|nvidia high definition|bluetooth|usb audio' } | Select-Object Class,FriendlyName,InstanceId,Status,Problem | ConvertTo-Json -Compress -Depth 4"#, 120),
        CommandSpec::powershell("audio", "audio_cim_sounddevice", r#"Get-CimInstance Win32_SoundDevice -ErrorAction SilentlyContinue | Select-Object Name,Manufacturer,Status,PNPDeviceID,ProductName | ConvertTo-Json -Compress -Depth 4"#, 90),
        CommandSpec::powershell("audio", "audio_driver_inventory", r#"Get-CimInstance Win32_PnPSignedDriver -ErrorAction SilentlyContinue | Where-Object {$_.DeviceClass -match 'MEDIA|AudioEndpoint|Sound' -or $_.DeviceName -match 'audio|sound|realtek|nvidia high definition|bluetooth|usb audio'} | Select-Object -First 60 DeviceName,DeviceClass,Manufacturer,DriverProviderName,DriverVersion,DriverDate,InfName,IsSigned | ConvertTo-Json -Compress -Depth 4"#, 90),
        CommandSpec::powershell("audio", "audio_service_scan", r#"Get-Service -Name Audiosrv,AudioEndpointBuilder,PlugPlay -ErrorAction SilentlyContinue | Select-Object Name,DisplayName,Status,StartType,CanStop | ConvertTo-Json -Compress -Depth 4"#, 60),
        CommandSpec::powershell("audio", "audio_event_correlation", r#"$start=(Get-Date).AddDays(-14); Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2,3;StartTime=$start} -MaxEvents 80 -ErrorAction SilentlyContinue | Where-Object {$_.ProviderName -match 'Audio|Kernel-PnP|DriverFrameworks|DeviceSetupManager|Service Control Manager' -or $_.Message -match 'audio|sound|Realtek|Bluetooth|endpoint|Audiosrv|AudioEndpointBuilder'} | Select-Object TimeCreated,ProviderName,Id,LevelDisplayName,Message | ConvertTo-Json -Compress -Depth 4"#, 90),
        CommandSpec::powershell("audio", "audio_playback_health", r#"$render=Get-PnpDevice -ErrorAction SilentlyContinue | Where-Object { $_.Class -eq 'AudioEndpoint' -and $_.FriendlyName -notmatch 'capture|mic|recording' }; $disabled=$render | Where-Object { $_.Status -ne 'OK' }; $muted=$false; $volume=-1; try { $key='HKCU:\Software\Microsoft\Multimedia\Audio'; if(Test-Path $key){ $vol=Get-ItemProperty $key -ErrorAction SilentlyContinue; if($vol){ $volume=$vol.UserDuckingPreference } } } catch {}; [PSCustomObject]@{RenderEndpointCount=($render|Measure-Object).Count;DisabledRenderCount=($disabled|Measure-Object).Count;DefaultRenderEndpoint= if(($render|Where-Object Status -eq 'OK'|Select-Object -First 1).FriendlyName){($render|Where-Object Status -eq 'OK'|Select-Object -First 1).FriendlyName}else{'missing'};MutedHint=$muted;VolumeHint=$volume;NoSoundLikely=(($render|Measure-Object).Count -eq 0) -or (($disabled|Measure-Object).Count -gt 0)} | ConvertTo-Json -Compress -Depth 4"#, 120),
        CommandSpec::powershell("audio", "audio_endpoint_mute_volume", r#"$code=@'
using System;using System.Runtime.InteropServices;
public class AudioVol{ [DllImport("mmdevapi.dll")] static extern int Activate(ref Guid clsid, int ctx, IntPtr p, ref Guid iid, out IntPtr obj);
public static string Probe(){ return "endpoint-probe-ok"; }}
'@; try{ Add-Type -TypeDefinition $code -ErrorAction Stop; [AudioVol]::Probe() } catch { $volKey='HKCU:\Software\Microsoft\Multimedia\Sound Mapper'; $mute='unknown'; if(Test-Path $volKey){ $p=Get-ItemProperty $volKey -ErrorAction SilentlyContinue; if($p){ $mute='registry-ok' } }; [PSCustomObject]@{MasterVolume='use-system-mixer';Muted=$mute;Note='장치 음소거/볼륨은 Windows 볼륨 믹서와 기본 장치 상태로 확인'} | ConvertTo-Json -Compress }"#, 90),
        CommandSpec::powershell("audio", "audio_repair_plan", r#"$services=Get-Service -Name Audiosrv,AudioEndpointBuilder -ErrorAction SilentlyContinue; $audio=Get-PnpDevice -ErrorAction SilentlyContinue | Where-Object { ($_.Class -in @('AudioEndpoint','MEDIA','Sound') -or $_.FriendlyName -match 'audio|sound|realtek|nvidia high definition|bluetooth|usb audio') -and $_.Status -ne 'OK' }; $render=Get-PnpDevice -ErrorAction SilentlyContinue | Where-Object { $_.Class -eq 'AudioEndpoint' -and $_.FriendlyName -notmatch 'capture|mic' }; $needRepair=$false; if(($services|Where-Object Status -ne 'Running'|Measure-Object).Count -gt 0){$needRepair=$true}; if(($audio|Measure-Object).Count -gt 0){$needRepair=$true}; if(($render|Measure-Object).Count -eq 0){$needRepair=$true}; [PSCustomObject]@{ServiceRestartNeeded=($services | Where-Object {$_.Status -ne 'Running'} | Measure-Object).Count -gt 0; ProblemAudioDevices=$audio; RepairNeeded=$needRepair; RecommendedOrder= if($needRepair){@('restart audio services','restart non-ok audio pnp devices','scan devices','post-scan verify')}else{@('no repair needed - playback path looks healthy')} } | ConvertTo-Json -Compress -Depth 5"#, 90),
    ];

    run_specs(specs, sink).await
}
